### ISSUE TITLE
ot.enableInputs(); ot.disableInputs(); => inputs still enabled 

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#100]
After this code, inputs are still enabled:

            ot.enableInputs();
            ot.disableInputs();

But after this code, inputs are properly disabled:

            ot.enableInputs();
            setTimeout(ot.disableInputs, 50);

**Comment by qwiglydee** [comment]
Best solution for now:
- disabling to run immediately, to prevent any excessive triggering  
- enabling to queue to prevent prevent any other re-enabled inputs to react on the same event

**Comment by qwiglydee** [comment]
Also, I don't see any reason to disable and enable all inputs at the same time
