### ISSUE TITLE
ot.resetInputs() should reset the values of the associated vars

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#48]
doing ot.resetInputs seems not to change the values of the associated ot.page vars.
For example if I have a button that has `ot-input="pressed = true"`, I would expect the variable ``pressed`` to be reset to null when I call `resetInputs`, but in fact it is still `true` in the next trial. I also think it would be really useful as a concise way to reset the variables, better than `delete ot.page.myinput` especially when you have multiple inputs and you might forget to delete some/all of them.

**Comment by qwiglydee** [comment]
The very idea of bidirectional binding of inputs←→vars appears conceptually confusing: https://github.com/qwiglydee/otree-front/issues/11#issuecomment-1530899510 

I'm removing the feature for now to simplify things.

Maybe, in next milestone I'll introduce global `inputs` to keep track of all validated/parsed values, while keeping page vars under explicit control of scripts only.
