### ISSUE TITLE
Value of an empty text input is null rather than empty string

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#52]
I have an input like this:

    <input type="text" ot-input="foo" autocommit>

If you delete the text in this input, vars.foo is set to null, rather than empty string. I think empty string would be more reasonable, because that is consistent with JS. Also this means handler must check for null value.

**Comment by qwiglydee** [comment]
Generally, this should be a matter of validation and/or 'required' constraint.

For now, it's up to `onInput` to check the stuff, so i enabled it be empty.
