### ISSUE TITLE
ot-display= elements flash on the screen briefly

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#96]
Elements with ot-display= briefly flash on the screen when the page is loaded. How about we hide these elements (or the whole page) until they have been hidden via ot-display?

Or instead of setting the 'hidden' attribute, ot-display could set .style.display = 'none'. Then these elements could be initially hidden with this CSS which guarantees they will never be shown.

    [ot-display] {
        display: none;
    }

**Comment by qwiglydee** [comment]
They intended to be hidden initially, but that includes scanning all descendant inputs and hiding them also, which is time consuming.

I believe that could be optimized by immediately putting them 'hidden' 
and only scan descendants when they are toggled via show/hide.
